In [409]:
import os
base_path="azucena/BT"
os.listdir(base_path)

['.ipynb_checkpoints',
 'artifacts',
 'azucena_heat_engager_plus17.json',
 'azu_12bplus8_reina_v2.json',
 'azu_BT-5_reina.json',
 'azu_bt1_reina.json',
 'azu_db3_BTplus4_reina.json',
 'azu_heat_engager_plus17.csv',
 'azu_lib_plus8.json',
 'azu_lib_plus8.xlsx',
 'json2gbt.py']

In [410]:
interactions = os.listdir(f"{base_path}/artifacts")
interactions

['azucena_heat_engager_plus17.gbt',
 'azu_12bplus8_reina_v2.gbt',
 'azu_BT-5_reina.gbt',
 'azu_bt1_reina.gbt',
 'azu_db3_BTplus4_reina.gbt',
 'azu_lib_plus8.gbt']

In [414]:
import pygambit as gbt
import pandas as pd

bt4 = gbt.Game.read_game(f"{base_path}/artifacts/{interactions[4]}")
result = gbt.nash.lcp_solve(bt4)
eqm = result.equilibria[0]
bt4

Game(title='Azucena db3 (+4) into BT on Reina')

In [415]:
players = [x.label for x in bt4.players]
players

['Azucena', 'Reina']

In [417]:
payoff = f'{float(eqm.payoff(players[0])):.4f}'
print(f"{players[0]} Payoff: {payoff}")

Azucena Payoff: 1.5943

In [418]:
equilibria = []
for player in players:
    for strategy, dist in eqm[player]:
        dist_formatted = f"{100*float(dist):.2f}%"
        equilibria.append({"player": strategy.player.label,
                           "strategy": strategy.label,
                           "distribution": dist_formatted})
eq_df = pd.DataFrame(equilibria)
eq_df

     player     strategy distribution
0   Azucena         BT.1        0.00%
1   Azucena       BT.1+2        8.89%
2   Azucena         BT.3       24.27%
3   Azucena       BT.1+3        0.00%
4   Azucena         BT.4       34.22%
5   Azucena      BT.2(2)       14.17%
6   Azucena       BT.3+4        0.00%
7   Azucena     B (exit)        0.00%
8   Azucena          qcb       18.45%
9   Azucena           d1        0.00%
10    Reina            B       52.06%
11    Reina           DB        0.00%
12    Reina          112        2.34%
13    Reina          DB1        8.21%
14    Reina        SSR~b       10.23%
15    Reina        SSL~b        0.00%
16    Reina  Power Crush        0.00%
17    Reina     Hop Kick        0.00%
18    Reina    Low Parry       27.15%

In [10]:
strategies = []
for player in players:
    for strategy in bt4.players[player].strategies:
        strategies.append({"player": player, 
                           "strategy": strategy.label, 
                           "strategy_value": f"{float(eqm.strategy_value(strategy)):.4f}",
                           })

In [11]:
strat_df = pd.DataFrame(strategies)
strat_df

     player     strategy strategy_value
0   Azucena         BT.1        -9.9835
1   Azucena       BT.1,2       -25.5235
2   Azucena       BT.1,4        -7.9626
3   Azucena       BT.1+2        -8.0887
4   Azucena         BT.3         6.5439
5   Azucena       BT.1+3        -7.4100
6   Azucena         BT.4        -0.4684
7   Azucena      BT.2(2)         6.5439
8   Azucena       BT.4,3         4.5308
9   Azucena       BT.3+4        -6.1590
10  Azucena     B (exit)         3.0631
11  Azucena          qcb         6.5439
12  Azucena           d1         0.5774
13    Reina            B        -6.5439
14    Reina           DB        -6.5439
15    Reina          112       -30.3013
16    Reina          DB1       -15.7908
17    Reina        SSR~b       -22.7615
18    Reina        SSL~b       -22.7615
19    Reina  Power Crush       -17.4405
20    Reina     Hop Kick        -6.5439

In [12]:
eq_df.merge(strat_df, on=["player","strategy"])

     player     strategy distribution strategy_value
0   Azucena         BT.1        0.00%        -9.9835
1   Azucena       BT.1,2        0.00%       -25.5235
2   Azucena       BT.1,4        0.00%        -7.9626
3   Azucena       BT.1+2        0.00%        -8.0887
4   Azucena         BT.3       28.45%         6.5439
5   Azucena       BT.1+3        0.00%        -7.4100
6   Azucena         BT.4        0.00%        -0.4684
7   Azucena      BT.2(2)       42.68%         6.5439
8   Azucena       BT.4,3        0.00%         4.5308
9   Azucena       BT.3+4        0.00%        -6.1590
10  Azucena     B (exit)        0.00%         3.0631
11  Azucena          qcb       28.87%         6.5439
12  Azucena           d1        0.00%         0.5774
13    Reina            B       76.19%        -6.5439
14    Reina           DB       14.18%        -6.5439
15    Reina          112        0.00%       -30.3013
16    Reina          DB1        0.00%       -15.7908
17    Reina        SSR~b        0.00%       -22.7615
18    Reina        SSL~b        0.00%       -22.7615
19    Reina  Power Crush        0.00%       -17.4405
20    Reina     Hop Kick        9.62%        -6.5439

In [13]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 '.vscode',
 'azucena',
 'create_gbt.sh',
 'notes.txt',
 'PyGambit Tekken 8.ipynb',
 'pygambit test.ipynb',
 'README.md',
 'reina_plus1.json']

In [14]:
ops = ["BT.1", "BT.1,2", "BT.1,4", "BT.1+2", "BT.3", "BT.1+3", "BT.4", "BT.2(2)", "BT.4,3", "BT.3+4",
        "B (exit)", "qcb", "d1"]

In [15]:
len(ops)

13

In [16]:
b = {
    "title": "Azucena db3 (+4) into BT on Reina",
    "P1": "Azucena",
    "P2": "Reina",
    "P1-strats": ["BT.1", "BT.1,2", "BT.1,4", "BT.1+2", "BT.3", "BT.1+3", "BT.4", "BT.2(2)", "BT.4,3", "BT.3+4",
        "B (exit)", "qcb", "d1"
    ],
    "P2-strats": ["B", "DB", "112", "DB1", "SSR~b", "SSL~b", "Power Crush", "Hop Kick"],
    "comment": "Azucena db3 (+4) into BT on Reina",
    "payoffs": [
        [-0.22, -76, 10, -5, -23, 10, 10, 10],
        [-23.52, -76, 33, -5, 32, 32, 33, 33],
        [-0.22, -76, 31, -5, 30, 30, 31, 31],
        [-23, 17, 73, 73, 17, 17, 73, 73],
        [23, -34, -24, -6, 23, 23, 41, -64],
        [0, -76, 0, -5, 0, 0, 35, 35],
        [-5.68, 15, 18, 18, 18, 18, -8, 18],
        [0, 38, 41, 41, 38, 38, -8, 12],
        [-43, 36, 39, 39, 36, 36, 13, 39],
        [0, 81, -38, 81, -76, 0, -28, -64],
        [0, 0, 0, 0, 0, 0, 31.83, 31.83],
        [0, 0, 68, 0, 0, 0, 31.83, 68]
    ]
}

In [17]:

len(b["P1-strats"])

13

In [18]:
for i in b["payoffs"]:
    print(len(i))

8
8
8
8
8
8
8
8
8
8
8
8

In [19]:
0.4511*-44

-19.8484

how much does the threat of the other options reduce the damage taken by BT.3,4 on block?
simple case where there is only one payoff: (sum of probabilities of defender's gto winning options) * payoff
multiple unique payoffs: sum of (probability of gto winning option) * payoff

In [364]:
os.listdir(base_path)

['.ipynb_checkpoints',
 'artifacts',
 'azu_12bplus8_reina_v2.json',
 'azu_BT-5_reina.json',
 'azu_bt1_reina.json',
 'azu_db3_BTplus4_reina.json',
 'azu_heat_engager_plus17.csv',
 'json2gbt.py',
 'old',
 'Untitled.ipynb']

In [21]:
import os
os.listdir(base_path)

['.ipynb_checkpoints',
 'artifacts',
 'azucena_heat_engager_plus17.json',
 'azu_12bplus8_reina_v2.json',
 'azu_BT-5_reina.json',
 'azu_bt1_reina.json',
 'azu_db3_BTplus4_reina.json',
 'azu_heat_engager_plus17.csv',
 'azu_lib_plus8.xlsx',
 'json2gbt.py',
 'old',
 'Untitled.ipynb',
 '~$azu_lib_plus8.xlsx']

In [399]:
attribs = pd.read_excel(f"{base_path}/azu_lib_plus8.xlsx", sheet_name=0)
attribs

       key                                              value
0    title                        Azucena LIB (+8) with Reina
1       P1                                            Azucena
2       P2                                              Reina
3  comment  Azucena LIB (+8) with Reina BT (-9), LIB.1, LI...

In [400]:
atr = {}
for index, row in attribs.iterrows():
    atr[row['key']] = row['value']
atr

{'title': 'Azucena LIB (+8) with Reina',
 'P1': 'Azucena',
 'P2': 'Reina',
 'comment': 'Azucena LIB (+8) with Reina BT (-9), LIB.1, LIB.4, LIB.3, LIB (+3), LIB.3 needs BT (+2)\nLIB.4 needs LIB (-3)\nis CH LIB.4 hit confirmable?\n LIB.4 on hit (LIB (+10)) maybe?\nlearn ch lib 4,1 combo\nssl b vs lib 1+2 weird ass combo route'}

In [401]:
df = pd.read_excel(f"{base_path}/azu_lib_plus8.xlsx", sheet_name=1)
df

,strats,B,DB,112,DB1,SSR~b,SSL~b,Power Crush,Hop Kick,Low parry
0,LIB.1,4,-76,16,-5,16,16,16.0,16.0,-76
1,"LIB.1,2",-76,-76,36,-6,34,34,36.0,36.0,-76
2,LIB.2,0,21,25,25,21,21,25.0,25.0,21
3,LIB.3,15,-5,18,18,15,15,18.0,18.0,-45
4,"LIB.3,1",-8,-23,38,38,-8,-8,38.0,38.0,-45
5,LIB.4,0,14,16,16,14,14,-9.0,16.0,14
6,"LIB.4,1",-76,24,66,66,24,24,1.0,66.0,24
7,"LIB.4,1,2",-76,1,59,59,1,1,1.0,59.0,1
8,"LIB.4, 2",-28,35,30,30,35,35,12.0,30.0,35
9,LIB.3+4,7,-76,48,-5,43,43,2.0,48.0,-76
10,LIB.1+2,-43,80,70,70,72,23,0.0,46.0,80
11,LIB.db,0,0,0,0,0,0,34.5,34.5,0
12,"LIB.d4,4",32,-76,-24,-6,32,32,34.0,-64.0,-45
13,LIB.uf1+2,0,-76,40,40,0,0,40.0,40.0,-76

In [402]:
 atr["P1-strats"] = df.strats.tolist()
 atr["P2-strats"] = df.columns.tolist()[1:]
dfc = df.drop(columns=df.columns[0]).values.tolist()
 atr["payoffs"] = dfc

In [403]:
import json
with open(f"{base_path}/azu_lib_plus8.json","w") as f:
    json.dump(atr, f)

In [404]:
df = pd.read_csv(f"{base_path}/azu_heat_engager_plus17.csv")
df

  strats     B  DB  Low Parry
0  ff3,2   8.0  30         30
1  ff3+4  10.0  46         46
2    db3  16.0  -5         16
3   d1+2   4.2 -18         18
4    db4  13.0 -34        -43
5    df2 -28.0  66         66

In [405]:
# Remove the first column
dfc = df.drop(columns=df.columns[0]).values.tolist()
dfc

[[8.0, 30.0, 30.0],
 [10.0, 46.0, 46.0],
 [16.0, -5.0, 16.0],
 [4.2, -18.0, 18.0],
 [13.0, -34.0, -43.0],
 [-28.0, 66.0, 66.0]]

In [406]:
js = {"title": "Azucena Heat Engager (+17)",
"P1": "Azucena",
"P2": "Reina",
 "P1-strats": df.strats.tolist(),
 "P2-strats": df.columns.tolist()[1:],
 "comment": "Azucena Heat Engager (+17). May need to look at d1+2 oki.",
 "payoffs": dfc
}

In [407]:
import json
with open(f"{base_path}/azucena_heat_engager_plus17.json","w") as f:
    json.dump(js, f)

In [408]:
{
    "title": "Azucena db3 (+4) into BT on Reina",
    "P1": "Azucena",
    "P2": "Reina",
    "P1-strats": ["BT.1", "BT.1,2", "BT.1,4", "BT.1+2", "BT.3", "BT.1+3", "BT.4", "BT.2(2)",
        "BT.4,3", "BT.3+4",
        "B (exit)", "qcb", "d1"
    ],
    "P2-strats": ["B", "DB", "112", "DB1", "SSR~b", "SSL~b", "Power Crush", "Hop Kick"],
    "comment": "Azucena db3 (+4) into BT on Reina. BT4, BT.4,3 requires upstream recalculation on change",
    "payoffs": [
        [-0.22, -76, 10, -5, -23, 10, 10, 10],
        [-23.52, -76, 33, -5, -23, 32, 33, 33],
        [-0.22, -76, 31, -5, -23, 30, 31, 31],
        [-23, 17, 73, 67, 17, 17, -6, 14],
        [23, -34, -24, -6, 23, 23, 41, -64],
        [0, -76, 0, -5, -76, 0, 35, -64],
        [-5.68, 15, -24, -6, 15, 15, -8, 52],
        [0, 38, -24, -6, -75, 15, -8, 12],
        [-19.85, 36, -24, -6, 36, 36, 13, 44],
        [0, 0, -38, 81, -76, 76, -28, -64],
        [0, 0, 0, 0, 0, 0, 31.83, 31.83],
        [0, 0, 68, 0, 0, 0, 31.83, 68],
        [0, 0, 6, 6, 6, 6, 6, 6]
    ]
}

{'title': 'Azucena db3 (+4) into BT on Reina',
 'P1': 'Azucena',
 'P2': 'Reina',
 'P1-strats': ['BT.1',
  'BT.1,2',
  'BT.1,4',
  'BT.1+2',
  'BT.3',
  'BT.1+3',
  'BT.4',
  'BT.2(2)',
  'BT.4,3',
  'BT.3+4',
  'B (exit)',
  'qcb',
  'd1'],
 'P2-strats': ['B',
  'DB',
  '112',
  'DB1',
  'SSR~b',
  'SSL~b',
  'Power Crush',
  'Hop Kick'],
 'comment': 'Azucena db3 (+4) into BT on Reina. BT4, BT.4,3 requires upstream recalculation on change',
 'payoffs': [[-0.22, -76, 10, -5, -23, 10, 10, 10],
  [-23.52, -76, 33, -5, -23, 32, 33, 33],
  [-0.22, -76, 31, -5, -23, 30, 31, 31],
  [-23, 17, 73, 67, 17, 17, -6, 14],
  [23, -34, -24, -6, 23, 23, 41, -64],
  [0, -76, 0, -5, -76, 0, 35, -64],
  [-5.68, 15, -24, -6, 15, 15, -8, 52],
  [0, 38, -24, -6, -75, 15, -8, 12],
  [-19.85, 36, -24, -6, 36, 36, 13, 44],
  [0, 0, -38, 81, -76, 76, -28, -64],
  [0, 0, 0, 0, 0, 0, 31.83, 31.83],
  [0, 0, 68, 0, 0, 0, 31.83, 68],
  [0, 0, 6, 6, 6, 6, 6, 6]]}

In [92]:
number_to_letter(len(df.columns))

'C'

## Writing to Excel Example

In [93]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

def number_to_letter(number):
    """
    Converts a number (1-26) to its corresponding letter in the English alphabet.
    
    Args:
        number (int): The input number (1-26).
        
    Returns:
        str: The corresponding letter if the input is valid.
        
    Raises:
        ValueError: If the number is outside the range 1-26.
    """
    if not (1 <= number <= 26):
        raise ValueError("Input must be an integer between 1 and 26.")
    return str(chr(64 + number))

# Example usage
l = number_to_letter(1)

# Sample data for the table
data = {
    "Column 1": [1, 2, 3],
    "Column 2": ["A", "B", "C"],
    "Column 3": [10.5, 20.5, 30.5]
}

# Create a pandas DataFrame
df = pd.DataFrame(data)

# Define title and metadata
title = "Professional Report"
metadata = {
    "Created by": "Your Name",
    "Date": "2025-01-13",
    "Description": "This file contains a sleek and professional design."
}

# File path
output_file = "sleek_example.xlsx"

# Define sleek styles
title_font = Font(size=18, bold=True, color="000000")  # Black, bold, large font
metadata_key_font = Font(size=12, bold=True, color="333333")  # Dark gray for keys
metadata_value_font = Font(size=12, color="000000")  # Black for values
header_font = Font(size=12, bold=True, color="FFFFFF")  # White for table headers
header_fill = PatternFill(start_color="4F81BD", end_color="4F81BD", fill_type="solid")  # Light blue
border_style = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin")
)
alignment_center = Alignment(horizontal="center", vertical="center")

# Write the DataFrame to Excel
with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    # Write the table data
    df.to_excel(writer, index=False, startrow=5, sheet_name="Sheet1")
    
    # Access the workbook and sheet
    workbook = writer.book
    sheet = writer.sheets["Sheet1"]
    
    # Last column of dataset
    ending_col = number_to_letter(len(df.columns))
    
    # Write the title
    sheet.merge_cells(f"A1:{ending_col}1")  # Merge cells for the title
    sheet["A1"] = title
    sheet["A1"].font = title_font
    sheet["A1"].alignment = alignment_center
    
    # Write the metadata
    row = 2
    for key, value in metadata.items():
        sheet[f"A{row}"] = key
        sheet[f"A{row}"].font = metadata_key_font
        sheet[f"B{row}"] = value
        sheet[f"B{row}"].font = metadata_value_font
        row += 1
    
    # Apply sleek styles to the table header
    for cell in sheet[6]:  # Header row is the 6th row
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = alignment_center
        cell.border = border_style
    
    # Apply borders to the data table
    for row in sheet.iter_rows(min_row=7, max_row=7 + len(df), min_col=1, max_col=len(df.columns)):
        for cell in row:
            cell.border = border_style

    # Adjust column widths
    for col in sheet.columns:
        max_length = 0
        col_letter = get_column_letter(col[0].column)  # Get the column letter
        for cell in col:
            try:  # Necessary to handle cases where the cell value is None
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        sheet.column_dimensions[col_letter].width = max_length + 2  # Add some padding

print(f"File '{output_file}' created successfully!")

File 'sleek_example.xlsx' created successfully!

## Writing Multiple Dataframes

In [94]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment, Font

# Example DataFrames
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Catherine"],
    "Age": [25, 30, 35],
    "Occupation": ["Engineer", "Doctor", "Scientist"]
})

df2 = pd.DataFrame({
    "Product": ["Laptop", "Tablet", "Phone"],
    "Price": [1000, 500, 700],
    "Quantity": [10, 20, 30]
})

# Define titles for each sheet
titles = {"Sheet1": "Employee Information", "Sheet2": "Product Details"}

# File path for the Excel file
file_path = "multiple_dataframes.xlsx"

# Write DataFrames to Excel
with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
    # Write each DataFrame to a separate sheet
    df1.to_excel(writer, index=False, sheet_name="Sheet1")
    df2.to_excel(writer, index=False, sheet_name="Sheet2")

# Apply styling and column width adjustments
wb = load_workbook(file_path)

for sheet_name, title in titles.items():
    ws = wb[sheet_name]

    # Insert and style the title
    ws.insert_rows(1)  # Add a blank row at the top
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(ws[1]))  # Merge title across columns
    title_cell = ws.cell(row=1, column=1)
    title_cell.value = title
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    title_cell.font = Font(bold=True, size=14)

    # Adjust column widths
    for col in ws.columns:
        max_length = 0
        col_letter = get_column_letter(col[0].column)  # Get the column letter
        for cell in col:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        ws.column_dimensions[col_letter].width = max_length + 2  # Add padding

# Save the workbook with styles
wb.save(file_path)

## Create GTO Distributions

In [359]:
import pygambit as gbt
import pandas as pd

def round_float(n, precision):
    """
        Rounds a float to specified precision. If precision=0, convert to int.
        
        Args:
            n (float): Number to be rounded
            precision (int): Number of decimal places.
        
        Returns:
            r (float|int): Returns the rounded number.
    """
    if precision < 0:
        raise ValueError("Precision must be greater than or equal to zero.")
        
    if precision == 0:
        r = round(n, precision)
        return int(r)
    
    return round(n, precision)

def full_path(gbt_filename, base_path=None):
    if base_path is None:
        path = gbt_filename
    else:
        path = f"{base_path}/{gbt_filename}"
    return path
    

def create_gto_distribution(gbt_filename, base_path=None, precision=2, drop_zeros=False, no_prec_percent=False):
    """
    Converts a number (1-26) to its corresponding letter in the English alphabet.
    
    Args:
        gbt_filename (str): Filename for .gbt file being analyzed.
        base_path (str): Base directory where file is located.
        precision (int): Number of decimal places to round up to.
        drop_zeros (bool): Indicate whether to drop options with 0% distribution.
        
    Returns:
        df: DataFrame containing the players, strategies, and distributions.
        metadata: 
        
    Raises:
        ValueError: If the number is outside the range 1-26.
    """
    if not gbt_filename.endswith(".gbt"):
        raise ValueError("Only .gbt files are supported.")
    
    df = None
    metadata = {}
    path = full_path(gbt_filename, base_path)

    bt4 = gbt.Game.read_game(path)
    result = gbt.nash.lcp_solve(bt4)
    eqm = result.equilibria[0]
    
    players = [x.label for x in bt4.players]
    
    # Round payoff to number of decimals specified by precision
    payoff = round_float(float(eqm.payoff(players[0])), precision)
    
    # Get GTO distributions
    equilibria = []
    
    for player in players:
        for strategy, dist in eqm[player]:
            if drop_zeros and float(dist) == 0:
                continue
                
            # Get Strategy Distribution
            dist_r = round_float(100*float(dist), precision)
            dist_formatted = f"{dist_r}%"
            
            if no_prec_percent:
                dist_formatted = float(dist)
            
            # Get Strategy Payoff
            strat_val = float(eqm.strategy_value(strategy))
            strat_val_r = round_float(strat_val, precision)
            
            # Create row
            equilibria.append({"player": strategy.player.label,
                               "strategy": strategy.label,
                               "distribution": dist_formatted,
                               "strategy_value": strat_val_r})

    # Convert to pandas dataframe
    df = pd.DataFrame(equilibria)
    
    metadata = {
        "title": bt4.title,
        "P1": players[0],
        "P2": players[1],
        "Payoff": payoff, 
        "Comment": bt4.comment,
    }
    
    return df, metadata

In [360]:
base_path = "azucena/BT/artifacts"

In [356]:
import os
os.listdir(base_path)

['azucena_heat_engager_plus17.gbt',
 'azu_12bplus8_reina_v2.gbt',
 'azu_BT-5_reina.gbt',
 'azu_bt1_reina.gbt',
 'azu_db3_BTplus4_reina.gbt',
 'azu_lib_plus8.gbt']

In [362]:
create_gto_distribution("azu_12bplus8_reina_v2.gbt", 
                         base_path=base_path, 
                         precision=0, 
                         drop_zeros=True,
                        no_prec_percent=True
                        )

(    player  strategy  distribution  strategy_value
 0  Azucena      BT.3      0.284519               7
 1  Azucena   BT.2(2)      0.426778               7
 2  Azucena       qcb      0.288703               7
 3    Reina         B      0.761947              -7
 4    Reina        DB      0.141819              -7
 5    Reina  Hop Kick      0.096234              -7,
 {'title': 'Azucena 1,2~B BT (+8) on Reina',
  'P1': 'Azucena',
  'P2': 'Reina',
  'Payoff': 7,
  'Comment': 'Azucena 1,2~B BT (+8) on Reina'})

## Create Excel File

In [390]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
import os

def excel_nformat_precision(precision):
    """
    Create an excel number format string based on precision.
    """
    if precision <= 0:
        return '0%'
    s = '0.'
    for i in range(1, precision+1):
        s+='0'
    return s+'%'

def create_excel_file(out_filename, input_dir, output_dir=None, precision=0, drop_zeros=True):
    """
    Create an excel file which contains all the nash equilibrium payoffs computed for .gbt files in input_dir.
    
    Args:
        out_filename (str): Name of the output file.
        input_dir (str): Folder containing .gbt files
        output_dir (str|Optional): optional output directory for the excel file
        precision (int): Precision for float values.
        drop_zeros (bool): Whether to drop zeros from distributions.
    
    Returns:
        Writes excel file.
    """
    files = os.listdir(input_dir)
    
    gto_distributions = []
    
    # Create GTO Distributions
    for filename in files:
        if filename.endswith(".gbt"):
            df, metadata = create_gto_distribution(filename, 
                                                   base_path=input_dir, 
                                                   precision=precision, 
                                                   drop_zeros=drop_zeros,
                                                   no_prec_percent=True)
            gto_distributions.append({'df': df, 'metadata': metadata})
    
    out_path = full_path(out_filename, output_dir)
    
    # Define sleek styles
    title_font = Font(size=18, bold=True, color="000000")  # Black, bold, large font
    metadata_key_font = Font(size=12, bold=True, color="333333")  # Dark gray for keys
    metadata_value_font = Font(size=12, color="000000")  # Black for values
    header_font = Font(size=12, bold=True, color="FFFFFF")  # White for table headers
    header_fill = PatternFill(start_color="4F81BD", end_color="4F81BD", fill_type="solid")  # Light blue
    border_style = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin")
    )
    title_border_style = Border(
        bottom=Side(style="thin")
    )
    alignment_center = Alignment(horizontal="center", vertical="center")
    
    # Define Yellow Neutral Style
    yellow_neutral_fill = PatternFill(start_color="FFF2CC", end_color="FFF2CC", fill_type="solid")  # Pale yellow
    yellow_neutral_font = Font(color="7F6000")  # Dark brownish-gray
    
    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        for gto_distribution in gto_distributions:
            df = gto_distribution["df"]
            metadata = gto_distribution["metadata"]
            
            # Sheet name
            sheet_name = metadata['title'][:min(32,len(metadata['title']))]
            
            #print(df)
            #print(metadata)
            
            # Starting row for gto data
            startrow = len(metadata.keys())+2

            df.to_excel(writer, index=False, startrow=startrow, sheet_name=sheet_name)

            workbook = writer.book
            sheet = writer.sheets[sheet_name]

            # Last column of dataset
            ending_col = number_to_letter(len(df.columns))

            # Write the title
            sheet.merge_cells(f"A1:{ending_col}1")  # Merge cells for the title
            sheet["A1"] = metadata["title"]
            sheet["A1"].font = title_font
            sheet["A1"].alignment = alignment_center

            # Highlight Payoff
            payoff_cell = "B4"
            sheet[payoff_cell].fill = yellow_neutral_fill
            sheet[payoff_cell].font = yellow_neutral_font
            sheet[payoff_cell].border = border_style

            # Add border to title
            for l in range(1, len(df.columns)+1):
                sheet[f"{number_to_letter(l)}1"].border = title_border_style

            row = 2
            metadata.pop('title', None)
            for key, value in metadata.items():
                sheet[f"A{row}"] = key
                sheet[f"A{row}"].font = metadata_key_font
                sheet[f"A{row}"].alignment = Alignment(wrap_text=True)
                sheet[f"B{row}"] = value
                sheet[f"B{row}"].font = metadata_value_font
                sheet[f"B{row}"].alignment = Alignment(wrap_text=True)
                row += 1

            # Apply sleek styles to the table header
            for cell in sheet[startrow+1]:  # Header row is the 6th row
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = alignment_center
                cell.border = border_style

            # Apply borders to the data table and Adjust precision on distribution column
            fmt_string = excel_nformat_precision(precision)
            for row in sheet.iter_rows(min_row=startrow+1, max_row=startrow + len(df) + 1, min_col=1, max_col=len(df.columns)):
                for cell in row:
                    cell.border = border_style
                    cell.alignment = Alignment(wrap_text=True)

                    # Distribution column formatting
                    if cell.column == 3:
                        cell.number_format = fmt_string

            # Adjust column widths
            for col in sheet.columns:
                max_length = 0
                col_letter = get_column_letter(col[0].column)  # Get the column letter
                for cell in col:
                    try:  # Necessary to handle cases where the cell value is None
                        # Excluding the "Comment" field
                        if cell.value and cell.coordinate != 'B6':
                            max_length = max(max_length, len(str(cell.value)))
                    except:
                        pass
                sheet.column_dimensions[col_letter].width = max_length + 2  # Add some padding

    return gto_distributions

In [392]:
gto = create_excel_file("azucena_gto.xlsx", input_dir=base_path, output_dir=None, precision=0, drop_zeros=True)